# IRC Connection Config

# Channel to connect
channel: "#mywolfychannel"
nickname: 'mywolfbot'
commander: '!'

# Authentication details
auth:
  username: mywolfbot
  password:
  hostname: internet
  mode: +iw
  realname: Wolves Bot

# Connection details
connection:
  host: irc.freenode.net
  port: 6667
  ssl: false

# Owners and Admins
owners:
  - user1
  - user2

admins:
  - user1
  - user2
