# Role Assignments
# Taken from lykos https://github.com/lykoss/lykos/blob/master/settings/wolfgame.py

roles  : [  seer, wolf, cursed, drunk, harlot, traitor, gunner, crow, angel, detective]
assign :
  4    : [  1,    1,    0,      0,     0,      0,       0,      0,    0,     0        ]
  6    : [  1,    1,    1,      0,     0,      0,       0,      0,    0,     0        ]
  8    : [  1,    1,    1,      1,     1,      1,       0,      0,    0,     0        ]
  10   : [  1,    2,    1,      1,     1,      1,       1,      0,    0,     0        ]
  12   : [  1,    2,    1,      1,     1,      1,       1,      1,    0,     1        ]
  15   : [  1,    3,    1,      1,     1,      1,       1,      1,    0,     1        ]
  17   : [  1,    3,    1,      1,     1,      1,       1,      1,    1,     1        ]
  18   : [  1,    3,    2,      1,     1,      1,       1,      1,    1,     1        ]
  20   : [  1,    4,    2,      1,     1,      1,       1,      1,    1,     1        ]
